Repository NotAShelf/nvf, pull requests merged in 2023-07, with the labels that each got.

#99 Feature/extra plugins
  lib/types/default.nix
  lib/types/plugins.nix
  modules/core/default.nix
Labels: enhancement

#95 feature/breadcrumbs
  configuration.nix
  docs/release-notes/rl-0.5.adoc
  flake.lock
  flake.nix
  lib/types/plugins.nix
  modules/lsp/config.nix
  modules/statusline/lualine/config.nix
  modules/ui/breadcrumbs/breadcrumbs.nix
  modules/ui/breadcrumbs/config.nix
  modules/ui/breadcrumbs/default.nix
  modules/ui/default.nix
  modules/visuals/config.nix
Labels: enhancement, TBD

#106 feature/denols
  docs/release-notes/rl-0.5.adoc
  modules/languages/ts.nix
Labels: enhancement

#111 feature/configurable leader key
  modules/basic/config.nix
  modules/basic/module.nix
Labels: enhancement

#112 feature/lsplines
  configuration.nix
  docs/release-notes/rl-0.5.adoc
  flake.lock
  flake.nix
  lib/types/plugins.nix
  modules/lsp/default.nix
  modules/lsp/lsplines/config.nix
  modules/lsp/lsplines/default.nix
  modules/lsp/lsplines/lsplines.nix
Labels: enhancement

#107 feature/rewrite nvimtree module
  configuration.nix
  docs/release-notes/rl-0.4.adoc
  lib/lua.nix
  modules/filetree/default.nix
  modules/filetree/nvimtree-lua/config.nix
  modules/filetree/nvimtree-lua/nvimtree-lua.nix
  modules/filetree/nvimtree/config.nix
  modules/filetree/nvimtree/default.nix
  modules/filetree/nvimtree/nvimtree.nix
  modules/statusline/lualine/config.nix
  modules/utility/binds/which-key/config.nix
Labels: enhancement, TBD, breaking
